export const MainGenres = {
  Action: 'action',
  Adventure: 'adventure',
  Comedy: 'comedy',
  Crime: 'crime',
  Educational: 'educational',
  Drama: 'drama',
  Fantasy: 'fantasy',
  Horror: 'horror',
  Musical: 'musical',
  Mystery: 'mystery',
  SciFi: 'scifi',
  War: 'war',
  Western: 'western',
};
