export const MusicGenres = {
    Blues: 'blues',
    Classical: 'classical',
    Country: 'country',
    EasyListening: 'easylistening',
    Electronic: 'electronic',
    Folk: 'folk',
    HipHop: 'hiphop',
    Jazz: 'jazz',
    Latin: 'latin',
    Metal: 'metal',
    Pop: 'pop',
    Punk: 'punk',
    RnB: 'rnb',
    Rock: 'rock',
}